openapi: 3.0.1
info:
  title: Site Specific Forecast
  description: This API provides weather forecast data for a requested coordinate defined by a latitude and longitude. The format of the data is GeoJSON.
  contact:
    name: Met Office
    url: https://www.metoffice.gov.uk/
  version: v0
security:
  - APIKey: []
paths:
  /point/hourly:
    get:
      summary: Find nearest forecast data that matches the request criteria
      operationId: GetHourlyForecast
      parameters:
        - name: dataSource
          in: query
          description: The request data source must be BD1.
          schema: {}
        - name: excludeParameterMetadata
          in: query
          description: If true, exclude parameter metadata in the response. If false or undefined, the parameter metadata is returned.
          schema: {}
        - name: includeLocationName
          in: query
          description: If true, include location name in the response. If false or undefined, no location name is returned.
          schema: {}
        - name: latitude
          in: query
          description: The request latitude value in range -85/+85 expressed as a decimal fraction.
          required: true
          schema: {}
        - name: longitude
          in: query
          description: The request longitude value in range -180/+180 expressed as a decimal fraction.
          required: true
          schema: {}
      responses:
        '200':
          description: The request was fulfilled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HourlyResponse'
        '400':
          description: The server could not service the request because it was malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '403':
          description: Access to the requested URL is forbidden.
          content: {}
        '404':
          description: The server could not service the request because the requested resource did not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '405':
          description: The server could not service the request because it does not support the requested HTTP action - only get requests are supported
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '415':
          description: The server could not service the request because the media type requested is not supported - this service only exposes json data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '500':
          description: The server encountered an internal error or misconfiguration and was unable to complete the request - this is not a recoverable error for a user of the API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
  /point/three-hourly:
    get:
      summary: Find nearest forecast data that matches the request criteria
      operationId: GetThreeHourlyForecast
      parameters:
        - name: dataSource
          in: query
          description: The request data source must be BD1.
          schema: {}
        - name: excludeParameterMetadata
          in: query
          description: If true, exclude parameter metadata in the response. If false or undefined, the parameter metadata is returned.
          schema: {}
        - name: includeLocationName
          in: query
          description: If true, include location name in the response. If false or undefined, no location name is returned.
          schema: {}
        - name: latitude
          in: query
          description: The request latitude value in range -85/+85 expressed as a decimal fraction.
          required: true
          schema: {}
        - name: longitude
          in: query
          description: The request longitude value in range -180/+180 expressed as a decimal fraction.
          required: true
          schema: {}
      responses:
        '200':
          description: The request was fulfilled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HourlyResponse'
        '400':
          description: The server could not service the request because it was malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '403':
          description: Access to the requested URL is forbidden.
          content: {}
        '404':
          description: The server could not service the request because the requested resource did not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '405':
          description: The server could not service the request because it does not support the requested HTTP action - only get requests are supported
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '415':
          description: The server could not service the request because the media type requested is not supported - this service only exposes json data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '500':
          description: The server encountered an internal error or misconfiguration and was unable to complete the request - this is not a recoverable error for a user of the API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
  /point/daily:
    get:
      summary: Find nearest forecast data that matches the request criteria
      operationId: GetDailyForecast
      parameters:
        - name: dataSource
          in: query
          description: The request data source must be BD1.
          schema: {}
        - name: excludeParameterMetadata
          in: query
          description: If true, exclude parameter metadata in the response. If false or undefined, the parameter metadata is returned.
          schema: {}
        - name: includeLocationName
          in: query
          description: If true, include location name in the response. If false or undefined, no location name is returned.
          schema: {}
        - name: latitude
          in: query
          description: The request latitude value in range -85/+85 expressed as a decimal fraction.
          required: true
          schema: {}
        - name: longitude
          in: query
          description: The request longitude value in range -180/+180 expressed as a decimal fraction.
          required: true
          schema: {}
      responses:
        '200':
          description: The request was fulfilled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DailyResponse'
        '400':
          description: The server could not service the request because it was malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '403':
          description: Access to the requested URL is forbidden.
          content: {}
        '404':
          description: The server could not service the request because the requested resource did not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '405':
          description: The server could not service the request because it does not support the requested HTTP action - only get requests are supported
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '415':
          description: The server could not service the request because the media type requested is not supported - this service only exposes json data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
        '500':
          description: The server encountered an internal error or misconfiguration and was unable to complete the request - this is not a recoverable error for a user of the API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VndError'
components:
  schemas:
    HourlyResponse:
      type: object
      properties:
        type: 
          type: string
        features: 
          type: array
          items: 
            type: object
            properties: 
              type: 
                type: string
              geometry: 
                type: object
                properties: 
                  type: 
                    type: string
                  coordinates: 
                    type: array
                    items: 
                      type: number
              properties: 
                type: object
                properties: 
                  location: 
                    type: object
                    properties: 
                      name: 
                        type: string
                  requestPointDistance: 
                    type: number
                  modelRunDate: 
                    type: string
                  timeSeries: 
                    type: array
                    items: 
                      type: object
                      properties: 
                        time: 
                          type: string
                        screenTemperature: 
                          type: number
                        maxScreenAirTemp: 
                          type: number
                        minScreenAirTemp: 
                          type: number
                        screenDewPointTemperature: 
                          type: number
                        feelsLikeTemperature: 
                          type: number
                        windSpeed10m: 
                          type: number
                        windDirectionFrom10m: 
                          type: integer
                          format: int32
                        windGustSpeed10m: 
                          type: number
                        max10mWindGust: 
                          type: number
                        visibility: 
                          type: integer
                          format: int32
                        screenRelativeHumidity: 
                          type: number
                        mslp: 
                          type: integer
                          format: int32
                        uvIndex: 
                          type: integer
                          format: int32
                        significantWeatherCode: 
                          type: integer
                          format: int32
                        precipitationRate: 
                          type: number
                          format: float
                        totalPrecipAmount: 
                          type: number
                          format: float
                        totalSnowAmount: 
                          type: integer
                          format: int32
                        probOfPrecipitation: 
                          type: integer
                          format: int32
    DailyResponse:
      type: object
      properties:
        type: 
          type: string
        features: 
          type: array
          items: 
            type: object
            properties: 
              type: 
                type: string
              geometry: 
                type: object
                properties: 
                  type: 
                    type: string
                  coordinates: 
                    type: array
                    items: 
                      type: number
              properties: 
                type: object
                properties: 
                  location: 
                    type: object
                    properties: 
                      name: 
                        type: string
                  requestPointDistance: 
                    type: number
                  modelRunDate: 
                    type: string
                  timeSeries: 
                    type: array
                    items: 
                      type: object
                      properties: 
                        time: 
                          type: string
                        midday10MWindSpeed: 
                          type: number
                        midnight10MWindSpeed: 
                          type: number
                        midday10MWindDirection: 
                          type: integer
                          format: int32
                        midnight10MWindDirection: 
                          type: integer
                          format: int32
                        midday10MWindGust: 
                          type: number
                        midnight10MWindGust: 
                          type: number
                        middayVisibility: 
                          type: integer
                          format: int32
                        midnightVisibility: 
                          type: integer
                          format: int32
                        middayRelativeHumidity: 
                          type: number
                        midnightRelativeHumidity: 
                          type: number
                        middayMslp: 
                          type: integer
                          format: int32
                        midnightMslp: 
                          type: integer
                          format: int32
                        nightSignificantWeatherCode: 
                          type: integer
                          format: int32
                        dayMaxScreenTemperature: 
                          type: number
                        nightMinScreenTemperature: 
                          type: number
                        dayUpperBoundMaxTemp: 
                          type: number
                        nightUpperBoundMinTemp: 
                          type: number
                        dayLowerBoundMaxTemp: 
                          type: number
                        nightLowerBoundMinTemp: 
                          type: number
                        nightMinFeelsLikeTemp: 
                          type: number
                        dayUpperBoundMaxFeelsLikeTemp: 
                          type: number
                        nightUpperBoundMinFeelsLikeTemp: 
                          type: number
                        dayLowerBoundMaxFeelsLikeTemp: 
                          type: number
                        nightLowerBoundMinFeelsLikeTemp: 
                          type: number
                        nightProbabilityOfPrecipitation: 
                          type: integer
                          format: int32
                        nightProbabilityOfSnow: 
                          type: integer
                          format: int32
                        nightProbabilityOfHeavySnow: 
                          type: integer
                          format: int32
                        nightProbabilityOfRain: 
                          type: integer
                          format: int32
                        nightProbabilityOfHeavyRain: 
                          type: integer
                          format: int32
                        nightProbabilityOfHail: 
                          type: integer
                          format: int32
                        nightProbabilityOfSferics: 
                          type: integer
                          format: int32
                        maxUvIndex: 
                          type: integer
                          format: int32
                        daySignificantWeatherCode: 
                          type: integer
                          format: int32
                        dayMaxFeelsLikeTemp: 
                          type: number
                        dayProbabilityOfPrecipitation: 
                          type: integer
                          format: int32
                        dayProbabilityOfSnow: 
                          type: integer
                          format: int32
                        dayProbabilityOfHeavySnow: 
                          type: integer
                          format: int32
                        dayProbabilityOfRain: 
                          type: integer
                          format: int32
                        dayProbabilityOfHeavyRain: 
                          type: integer
                          format: int32
                        dayProbabilityOfHail: 
                          type: integer
                          format: int32
                        dayProbabilityOfSferics: 
                          type: integer
                          format: int32
    VndError:
      title: VndError
      type: object
      properties:
        logref:
          type: string
        message:
          type: string
  securitySchemes:
    APIKey:
      type: apiKey
      description: The API Key generated with your Subscription in Weather DataHub, this must be set as 'apikey' in your header.
      name: apikey
      in: header
